sudo: required

services:
  - docker

before_install:
  - docker build -t operable/piper-testing -f Dockerfile.ci .

# Need the job ID in order to upload the Coveralls data
script:
  - docker run -it --rm --env="TRAVIS_JOB_ID=${TRAVIS_JOB_ID}" operable/piper-testing mix coveralls.travis

notifications:
  slack:
    secure: odOAuB/xARu+yemGsl1ZoF8kGZgt2l6UWo1mxUSJDmyXjw1ZD+Rsn7iPuaw7VUqav1D2NldQkRDIIyrssXQVLsAjECf1eIG9rAn0FABnFrodKVDUBa/pgH3SYOBwzgJY+/30hOZ6mKRo+bS63NMEwBcTgN8icdV66e9y+dVSub/0pmEGVD4o8KggQiPH/65B3HsXXgPct669GXFb1TTu0jKQv/g6nYDN7p6+A4Y53EyRryQkVblG+Uv6QNPDjrRnTyk35ny6yPSnwj9HVaFdvKir5X2FHpi7q7G8v8x1jDR5QrsefMF+pxtEFnmfz92CnOvLtS2GgrRBcft7o9Oyk0Xs+zEb8M39PtnkWD5lTJleMVs3KuFn2FbHo+F4/rbzYZEk+IWq9EJicOIpnyOS0Oef9BlGf15n9X/5+QNWooO1h/mBlcHI0tWeEe+4gstPrsNwoqvsxrCV1vt17Zfr+MUdDTOLFFGihwyMuuk6OlQW20O0Vn4lqO/qOArz9btsfTPTpuPDEWVf2nGBZhBbjuOoFHUE1s6OuHozT2uCNUVrU/hrbBhecwvo10zkezUYVMq9wdFMkS+EqZv0EpjyzukWLQ348/s+RZrZjmK5bvgDuR+8nVFCUYT9YFimVWDklrmJ4vtm3fmpCN2l2NP+bmgqXCTfHJj+SYo15ow4YlI=
